name: CI/CD workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  check-tests-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      fail-fast: true
      matrix:
        npm_command:
          [
            "npm run lint",
            "npm audit --production --audit-level=critical",
            "npm run test:ci",
          ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"
      - name: installation dependances
        run: npm ci
      - name: tests
        run: |
          ${{ npm_command }}
